[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["cd ../.. & npm install"]

[build]
builder = "NIXPACKS"
buildCommand = "npm run --prefix ../.. build"

[deploy]
startCommand = "npm run start"