[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["ls -a ../ & npm install"]

[build]
builder = "NIXPACKS"
buildCommand = "ls -a & npm run --prefix ../.. build"

[deploy]
startCommand = "ls -a & npm run start"