[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["npm install --prefix ../.."]

[build]
builder = "NIXPACKS"
buildCommand = "npm run --prefix ../.. build"

[deploy]
startCommand = "npm run start"