[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["ls -a & npm install"]

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run --prefix ./apps/website start"