[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "cd ./apps/website/ & ls -a & npm run start"