[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "ls -a ./apps & ls -a ./apps/website & npm run start"